"""Draws the program icon (a folder with a green "+") and writes:

  assets/icon.ico                      for the Windows .exe (16 ... 256 px)
  assets/icon.png                      256 px preview
  foldertemplatemaker/appicon.py       small PNGs embedded in the program (window icon)

Run it again only if you want to change the artwork (needs Pillow: pip install pillow).
The generated files are committed, so building the program does not need Pillow.
"""

from __future__ import annotations

import base64
import io
import os

from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BIG = 1024


def lerp(a, b, t):
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(3))


def vertical_gradient(size, top, bottom):
    w, h = size
    strip = Image.new("RGB", (1, h))
    for y in range(h):
        strip.putpixel((0, y), lerp(top, bottom, y / max(h - 1, 1)))
    return strip.resize((w, h))


def draw_icon() -> Image.Image:
    canvas = Image.new("RGBA", (BIG, BIG), (0, 0, 0, 0))

    # soft shadow under the folder
    shadow = Image.new("RGBA", (BIG, BIG), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle((110, 330, 930, 880), radius=70, fill=(0, 0, 0, 110))
    shadow = shadow.filter(ImageFilter.GaussianBlur(26))
    canvas.alpha_composite(shadow, (0, 22))

    d = ImageDraw.Draw(canvas)
    amber = (222, 158, 24, 255)
    # back of the folder, with its tab
    d.rounded_rectangle((90, 150, 450, 400), radius=52, fill=amber)
    d.rounded_rectangle((90, 250, 934, 820), radius=64, fill=amber)

    # front panel with a vertical gradient
    panel = (90, 355, 934, 860)
    mask = Image.new("L", (BIG, BIG), 0)
    ImageDraw.Draw(mask).rounded_rectangle(panel, radius=64, fill=255)
    gradient = vertical_gradient((panel[2] - panel[0], panel[3] - panel[1]),
                                 (255, 226, 140), (247, 183, 49))
    layer = Image.new("RGBA", (BIG, BIG), (0, 0, 0, 0))
    layer.paste(gradient, (panel[0], panel[1]))
    canvas.paste(layer, (0, 0), mask)

    # light edge along the top of the front panel
    d = ImageDraw.Draw(canvas)
    d.rounded_rectangle((panel[0] + 10, panel[1] + 8, panel[2] - 10, panel[1] + 30), radius=12,
                        fill=(255, 241, 190, 200))

    # green "+" badge
    cx, cy, r = 742, 712, 218
    d.ellipse((cx - r - 26, cy - r - 26, cx + r + 26, cy + r + 26), fill=(255, 255, 255, 255))
    d.ellipse((cx - r, cy - r, cx + r, cy + r), fill=(38, 150, 76, 255))
    bar, half = 52, 118
    d.rounded_rectangle((cx - half, cy - bar // 2, cx + half, cy + bar // 2), radius=bar // 2,
                        fill=(255, 255, 255, 255))
    d.rounded_rectangle((cx - bar // 2, cy - half, cx + bar // 2, cy + half), radius=bar // 2,
                        fill=(255, 255, 255, 255))
    return canvas


def png_bytes(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    return buffer.getvalue()


def main() -> None:
    big = draw_icon()
    master = big.resize((256, 256), Image.LANCZOS)
    master.save(os.path.join(HERE, "icon.png"), optimize=True)

    sizes = [(16, 16), (20, 20), (24, 24), (32, 32), (40, 40), (48, 48), (64, 64), (128, 128), (256, 256)]
    master.save(os.path.join(HERE, "icon.ico"), format="ICO", sizes=sizes)

    lines = ['"""Small PNG versions of the program icon, embedded so no image file is needed at run time.',
             "",
             "Generated by assets/make_icon.py - don't edit by hand.",
             '"""',
             ""]
    for size in (64, 32):
        data = base64.b64encode(png_bytes(big.resize((size, size), Image.LANCZOS))).decode("ascii")
        lines.append("PNG_%d = (" % size)
        for start in range(0, len(data), 76):
            lines.append('    "%s"' % data[start:start + 76])
        lines.append(")")
        lines.append("")
    with open(os.path.join(ROOT, "foldertemplatemaker", "appicon.py"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print("wrote icon.ico, icon.png and appicon.py")


if __name__ == "__main__":
    main()
